services:
  - type: web
    name: alias-game
    runtime: node
    buildCommand: yarn install && yarn build && yarn build:server
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
