services:
  - type: web
    name: alias-game
    runtime: node
    buildCommand: npm install --include=dev && npm run build && npm run build:server
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
