services:
  - type: web
    name: alias-game
    runtime: node
    buildCommand: npm install && npm run build && npm run build:server
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
